
package Pharmachy_Management_Final;

 
import java.awt.Graphics;
import java.awt.Graphics2D;
 
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jasmi
 */
public class Bill_Paid extends javax.swing.JFrame {

    Connection ct=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Statement st=null;
    public Bill_Paid(String bill,String supname,String num,String st) {
        initComponents();
        total.setVisible(false);
        jLabel7.setVisible(false);
        shows(supname,bill,num,st);
        shows2(supname, bill, num,st);
    }
    private Bill_Paid() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dat = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        deu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mobile :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(450, 100, 60, 20);

        dat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(dat);
        dat.setBounds(480, 50, 140, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField1);
        jTextField1.setBounds(510, 100, 110, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField2);
        jTextField2.setBounds(80, 100, 360, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 100, 60, 20);

        sl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sl.setForeground(new java.awt.Color(255, 255, 255));
        sl.setText("Sl");
        jPanel3.add(sl);
        sl.setBounds(30, 50, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(430, 50, 50, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No", "Date", "Ammount", "Paid", "Due"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(50, 130, 550, 380);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Paid");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(300, 520, 160, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Due");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(430, 520, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Ammount");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(130, 520, 130, 20);

        paid.setEditable(false);
        paid.setBackground(new java.awt.Color(255, 255, 255));
        paid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(paid);
        paid.setBounds(270, 540, 160, 30);

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel3.add(total);
        total.setBounds(130, 540, 140, 30);

        deu.setEditable(false);
        deu.setBackground(new java.awt.Color(255, 255, 255));
        deu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(deu);
        deu.setBounds(430, 540, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("..................................................................");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 600, 200, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Client Signature");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 620, 200, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Authorized Signature");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(400, 620, 200, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("..................................................................");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(400, 600, 200, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 630, 660);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Bill");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 580, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13);
        jLabel13.setBounds(670, 0, 50, 40);

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("-");
        jLabel105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel105MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel105);
        jLabel105.setBounds(630, 0, 40, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 80);

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));
        jPanel7.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(0, 40, 80, 23);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(630, 80, 90, 660);

        setSize(new java.awt.Dimension(721, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
void shows(String supname,String bill,String num,String st){
    int t=0,p=0,d=0,co=0;
          try {
                 sl.setText("Bill No :"+bill);
              jTextField2.setText(""+supname);
              jTextField1.setText(""+num);
               Date dtr = new Date();
             DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
              //  DateFormat dfm = new SimpleDateFormat("yyyy-MM");
             dat.setText(""+df.format(dtr));
             
              String coun="SELECT COUNT(`id`) FROM `purchase_total` WHERE `s_name`='"+supname+"'AND `status` = '"+st+"'";
              contest();
              
              ps=ct.prepareCall(coun);
              rs=ps.executeQuery();
              if(rs.next()){
            co=rs.getInt(1);
               }
              String s="SELECT `id`,`date`,(`ammount`)AS `Per Bill Ammount`,`paid`,(`total_ammount`-`paid`)AS`deu`FROM `pharmacy_management`.`purchase_total` WHERE `s_name`='"+supname+"'AND `status` = '"+st+"'";
              contest();
              DefaultTableModel dt=(DefaultTableModel) jTable1.getModel();
            ps=ct.prepareCall(s);
              rs=ps.executeQuery();
          
if(co<=5){
           
              while(rs.next()){
           dt.addRow(new Object[]{rs.getInt(1),
             rs.getDate(2),rs.getInt(3),rs.getInt(4),rs.getInt(5) });
                  
              }
}
else{
                co=co-5;
            int co2=0;
             
              while(rs.next()){
           if(co2==co){
           dt.addRow(new Object[]{rs.getInt(1),
             rs.getDate(2),rs.getInt(3),rs.getInt(4),rs.getInt(5) });
             
           }else{
           co2=co2+1;
           } 
              }}
          
              
          } catch (SQLException ex) {
              Logger.getLogger(Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
          }



}
void shows2(String supname,String bill,String num,String st){
    int t=0,p=0,d=0;
          try {
                 
              String s="SELECT `id`,`date`,(`ammount`)AS `Per Bill Ammount`,`paid`,(`total_ammount`-`paid`)AS`deu`FROM `pharmacy_management`.`purchase_total` WHERE `id`='"+bill+"' AND `status` = '"+st+"'";
              contest();
            
              ps=ct.prepareCall(s);
              rs=ps.executeQuery();
              if(rs.next()){
           
                paid.setText(""+rs.getInt(4));
              deu.setText(""+rs.getInt(5));
              
              }
              
              
          } catch (SQLException ex) {
              Logger.getLogger(Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
          }



}
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel105MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel105MouseClicked

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics pg, PageFormat pf, int PageNum){
                //To change body of generated methods, choose Tools | Templates.
                if(PageNum>0){
                    return NO_SUCH_PAGE;}
                Graphics2D g2=(Graphics2D) pg;
                g2.translate(pf.getImageableX(),pf.getImageableX());
                g2.scale(1,0.8);
                jPanel3.print(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        if(job.printDialog()==true){
            JOptionPane.showMessageDialog(this,"Print success..");
            try{
                job.print();
            }catch(PrinterException P){

            }
            dispose();

        }else{JOptionPane.showMessageDialog(this,"Failed...");}

    }//GEN-LAST:event_jButton2ActionPerformed
 public void contest() {
        try {
            ct = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_management", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
        } }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_Paid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dat;
    private javax.swing.JTextField deu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField paid;
    private javax.swing.JLabel sl;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
