/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmachy_Management_Final;
 
import java.awt.Graphics;
import java.awt.Graphics2D; 
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jasmi
 */
public class Madecine_Sells extends javax.swing.JFrame {

    Connection ct=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Statement st=null;
    int i=0;
    public Madecine_Sells(String status) {
        initComponents();
        show_madecine();
            statusl.setText(status);
    if(status.equals("Admin")){
      
      }
      else{   Sample_Button.setVisible(false);
      Sample_Button1.setVisible(false);
      Sample_Button2.setVisible(false);
          Sample_Button3.setVisible(false);
          Sample_Button4.setVisible(false);
      jButton4.setVisible(false);}
    }

    private Madecine_Sells() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        dat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        deu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        total1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Sample_Button = new javax.swing.JButton();
        Sample_Button1 = new javax.swing.JButton();
        Sample_Button2 = new javax.swing.JButton();
        sample_Bill_Button1 = new javax.swing.JButton();
        Sample_Button3 = new javax.swing.JButton();
        Sample_Button4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        statusl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sales");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(80, 0, 730, 40);

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("-");
        jLabel105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel105MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel105);
        jLabel105.setBounds(910, 0, 40, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(950, 0, 50, 40);

        jButton3.setBackground(new java.awt.Color(204, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Medecine info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(840, 50, 160, 23);

        jPanel6.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 40, 1010, 10);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicine" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(80, 140, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medicine");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 120, 80, 20);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 140, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock Quantity");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 120, 100, 20);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(380, 140, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 120, 80, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(80, 200, 210, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sales Quantity");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 180, 130, 20);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(300, 200, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Price");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 180, 100, 20);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(760, 220, 110, 40);

        jButton9.setBackground(new java.awt.Color(204, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(650, 220, 110, 40);

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setLayout(null);

        dat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(dat);
        dat.setBounds(470, 50, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Paid");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(270, 520, 160, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Due");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(430, 520, 170, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Ammount");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(130, 520, 130, 20);

        paid.setEditable(false);
        paid.setBackground(new java.awt.Color(255, 255, 255));
        paid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(paid);
        paid.setBounds(270, 540, 160, 30);

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel4.add(total);
        total.setBounds(130, 540, 140, 30);

        deu.setEditable(false);
        deu.setBackground(new java.awt.Color(255, 255, 255));
        deu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(deu);
        deu.setBounds(430, 540, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("..................................................................");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(60, 600, 200, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Client Signature");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(60, 620, 200, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Authorized Signature");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(400, 620, 200, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("..................................................................");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(400, 600, 200, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Madicine", "Sales Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 570, 350);

        total1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total1.setForeground(new java.awt.Color(255, 255, 255));
        total1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(total1);
        total1.setBounds(370, 370, 230, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(50, 270, 630, 430);

        jButton10.setBackground(new java.awt.Color(204, 0, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Print");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(700, 280, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(360, 0, 1010, 730);

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setLayout(null);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Stock");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(30, 280, 290, 40);

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(30, 80, 290, 40);

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Purchase");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(30, 120, 290, 40);

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Sales");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(30, 160, 290, 40);

        jButton8.setBackground(new java.awt.Color(204, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Madechine Info");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(30, 200, 290, 40);

        Sample_Button.setBackground(new java.awt.Color(204, 0, 0));
        Sample_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sample_Button.setForeground(new java.awt.Color(255, 255, 255));
        Sample_Button.setText("Sample Purchase");
        Sample_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sample_ButtonActionPerformed(evt);
            }
        });
        jPanel5.add(Sample_Button);
        Sample_Button.setBounds(30, 320, 290, 40);

        Sample_Button1.setBackground(new java.awt.Color(204, 0, 0));
        Sample_Button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sample_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Sample_Button1.setText(" Purchase Show");
        Sample_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sample_Button1ActionPerformed(evt);
            }
        });
        jPanel5.add(Sample_Button1);
        Sample_Button1.setBounds(30, 360, 290, 40);

        Sample_Button2.setBackground(new java.awt.Color(204, 0, 0));
        Sample_Button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sample_Button2.setForeground(new java.awt.Color(255, 255, 255));
        Sample_Button2.setText("Accounts");
        Sample_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sample_Button2ActionPerformed(evt);
            }
        });
        jPanel5.add(Sample_Button2);
        Sample_Button2.setBounds(30, 440, 290, 40);

        sample_Bill_Button1.setBackground(new java.awt.Color(204, 0, 0));
        sample_Bill_Button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sample_Bill_Button1.setForeground(new java.awt.Color(255, 255, 255));
        sample_Bill_Button1.setText(" Bill");
        sample_Bill_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample_Bill_Button1ActionPerformed(evt);
            }
        });
        jPanel5.add(sample_Bill_Button1);
        sample_Bill_Button1.setBounds(30, 240, 290, 40);

        Sample_Button3.setBackground(new java.awt.Color(204, 0, 0));
        Sample_Button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sample_Button3.setForeground(new java.awt.Color(255, 255, 255));
        Sample_Button3.setText("Pin");
        Sample_Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sample_Button3ActionPerformed(evt);
            }
        });
        jPanel5.add(Sample_Button3);
        Sample_Button3.setBounds(30, 480, 290, 40);

        Sample_Button4.setBackground(new java.awt.Color(204, 0, 0));
        Sample_Button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sample_Button4.setForeground(new java.awt.Color(255, 255, 255));
        Sample_Button4.setText("Sales Show");
        Sample_Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sample_Button4ActionPerformed(evt);
            }
        });
        jPanel5.add(Sample_Button4);
        Sample_Button4.setBounds(30, 400, 290, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 80, 370, 650);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(null);

        statusl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        statusl.setForeground(new java.awt.Color(153, 0, 0));
        statusl.setText("User");
        jPanel3.add(statusl);
        statusl.setBounds(0, 0, 140, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 370, 80);

        setSize(new java.awt.Dimension(1368, 724));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        show_quantity();
    }//GEN-LAST:event_jComboBox1ActionPerformed
void shows(){
       
             Date dt = new Date();
          DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
      
            DefaultTableModel dtt=(DefaultTableModel) jTable1.getModel();
            contest();
          i=Integer.parseInt(jTextField5.getText())+i;
            dtt.addRow(new Object[]{jComboBox1.getSelectedItem(),jTextField4.getText(),jTextField3.getText(),jTextField5.getText()});
           
        total1.setText(""+i);

}
    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             if(jTextField4.getText().isEmpty()){
                 JOptionPane.showMessageDialog(rootPane, "Madecine Price is Empty");
             }else if(jTextField3.getText().isEmpty()){
                 JOptionPane.showMessageDialog(rootPane, "Madecine Quantity is Empty");
             }else{
             
             int price=0,quan=0,stock=0;
        price=Integer.parseInt(jTextField4.getText());
          quan=Integer.parseInt(jTextField3.getText());
          stock=Integer.parseInt(jTextField2.getText());
         if(stock<quan){
             JOptionPane.showMessageDialog(rootPane, "Out Of Stock...");
         }else{ jTextField5.setText(""+price*quan);
         
         }
             }   
         }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jLabel105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel105MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel105MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
   LogingPage l=new LogingPage();
   l.setVisible(true);      
       dispose();
      
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Medicine_Info pr=new Medicine_Info(statusl.getText());
        pr.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Madecine_Stock s=new Madecine_Stock(statusl.getText());
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home_PAge hp=new Home_PAge(statusl.getText());
  hp.setVisible(true);
  dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  Madechine_Purchase ms=new Madechine_Purchase(statusl.getText());
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Madecine_Sells ms=new Madecine_Sells(statusl.getText());
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Medicine_Info mi=new Medicine_Info(statusl.getText());
        mi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
      char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE|| c==KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        if(jComboBox1.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(rootPane, "Medicine Name Is Empty...");
        }else{
             jTextField3.requestFocus();
         }}
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void Sample_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sample_ButtonActionPerformed
        Sample_Purchase s=new Sample_Purchase(statusl.getText());
        s.setVisible(true);
        dispose();

    }//GEN-LAST:event_Sample_ButtonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox1.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(rootPane, "Madecine is Empty");
            jComboBox1.requestFocus();
        }
        else if(jTextField3.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Sales Quantity  is Empty");
            jTextField3.requestFocus();
        }else if(jTextField5.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "T^otal Price is Empty");
            jTextField5.requestFocus();
        }else{
            try {
                contest();
                Date dt = new Date();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
int stockq=Integer.parseInt(jTextField2.getText());
int sellq=Integer.parseInt(jTextField3.getText());
            if(stockq<sellq){
            JOptionPane.showMessageDialog(rootPane," "+(sellq-stockq)+ " Medicines are out of stock...");
            
            
            }else{
                
                
                String s="INSERT INTO `pharmacy_management`.`sells`(`madecine`,`s_price`,`quantity`,`total price`,`date`) VALUES (?,?,?,?,?);";
                ps=ct.prepareCall(s);
               
                ps.setString(1,jComboBox1.getSelectedItem().toString());
                ps.setString(2,jTextField4.getText());
                ps.setString(3,jTextField3.getText());
                ps.setString(4,jTextField5.getText());
                ps.setString(5,df.format(dt));

                int m=ps.executeUpdate();
                if(m>0){
                    shows();
                    
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                     jComboBox1.setSelectedIndex(0);
                     jComboBox1.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Madecine Sales Failed.....");
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(Medicine_Info.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jTextField2.setText("");
       jTextField3.setText("");
        jTextField4.setText("");
         jTextField5.setText("");
         jComboBox1.setSelectedIndex(0);
         DefaultTableModel dt=(DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);
        total1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Sample_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sample_Button1ActionPerformed
        Purchase_Show ps=new Purchase_Show(statusl.getText());
        ps.setVisible(true);
        dispose();
    }//GEN-LAST:event_Sample_Button1ActionPerformed

    private void Sample_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sample_Button2ActionPerformed
        Accounts ps=new Accounts(statusl.getText());
        ps.setVisible(true);
        dispose();
    }//GEN-LAST:event_Sample_Button2ActionPerformed

    private void sample_Bill_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample_Bill_Button1ActionPerformed
     Home_PAge  h=new Home_PAge(statusl.getText());
     h.setVisible(true); 
     Bill_Paid_1 hp=new Bill_Paid_1(statusl.getText());
      
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_sample_Bill_Button1ActionPerformed

    private void Sample_Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sample_Button3ActionPerformed
        Create_Login_Pin ps=new Create_Login_Pin();
        ps.setVisible(true);
    }//GEN-LAST:event_Sample_Button3ActionPerformed

    private void Sample_Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sample_Button4ActionPerformed
        Sells_Show ps=new Sells_Show(statusl.getText());
        ps.setVisible(true);
        dispose();
    }//GEN-LAST:event_Sample_Button4ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics pg, PageFormat pf, int PageNum){
                //To change body of generated methods, choose Tools | Templates.
                if(PageNum>0){
                    return NO_SUCH_PAGE;}
                Graphics2D g2=(Graphics2D) pg;
                g2.translate(pf.getImageableX(),pf.getImageableX());
                g2.scale(1,0.8);
                jPanel4.print(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        if(job.printDialog()==true){
            JOptionPane.showMessageDialog(this,"Print success..");
            try{
                job.print();
            }catch(PrinterException P){

            }
            dispose();

        }else{JOptionPane.showMessageDialog(this,"Failed...");}
    }//GEN-LAST:event_jButton10ActionPerformed
public void contest() {
        try {
            ct = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_management", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Add_Supplier.class.getName()).log(Level.SEVERE, null, ex);
        } }
   void show_madecine(){
        try {
            contest();
            String s="SELECT `stock`.`Madicine_Name` FROM `stock`";
            
            
            st = ct.prepareCall(s);
            rs = st.executeQuery(s);
            while(rs.next()){
                jComboBox1.addItem(rs.getString(1));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Madecine_Sells.class.getName()).log(Level.SEVERE, null, ex);
        }
   
   
   
   }
     void show_quantity(){
        try {
            contest();
            String s="SELECT *FROM `stock` WHERE `Madicine_Name`='"+jComboBox1.getSelectedItem()+"'";
            
            
            st = ct.prepareCall(s);
            rs = st.executeQuery(s);
            while(rs.next()){
              int p=rs.getInt(2);
              int se=rs.getInt(3);
                int t=p-se;
                jTextField2.setText(""+t);
              
            }
            
            
            
            
            String mp="SELECT `s_price` FROM `purchase` WHERE `medecine`='"+jComboBox1.getSelectedItem()+"'";
             st = ct.prepareCall(mp);
            rs = st.executeQuery(mp);
            while(rs.next()){
              
                jTextField4.setText(""+rs.getInt(1));
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Madecine_Sells.class.getName()).log(Level.SEVERE, null, ex);
        }
   
   
   
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Madecine_Sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Madecine_Sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Madecine_Sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Madecine_Sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Madecine_Sells().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sample_Button;
    private javax.swing.JButton Sample_Button1;
    private javax.swing.JButton Sample_Button2;
    private javax.swing.JButton Sample_Button3;
    private javax.swing.JButton Sample_Button4;
    private javax.swing.JLabel dat;
    private javax.swing.JTextField deu;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField paid;
    private javax.swing.JButton sample_Bill_Button1;
    private javax.swing.JLabel statusl;
    private javax.swing.JTextField total;
    private javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
