
package Pharmachy_Management_Final;
 
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jasmi
 */
public class Purchase_Bill_Paid extends javax.swing.JFrame {

      Connection ct=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Statement st=null;
    public Purchase_Bill_Paid() {
        initComponents();
        showsname();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Bill");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 90, 90, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 110, 170, 80);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("0");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(190, 110, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Paid");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 90, 180, 20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(470, 10, 70, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier Name" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(20, 50, 170, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 0, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("0");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(370, 110, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deu");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(370, 90, 160, 20);

        jTextField5.setBackground(new java.awt.Color(204, 0, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 160, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Paid");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(190, 140, 170, 20);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 0, 0));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(370, 160, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Deu");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(370, 140, 160, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 60, 160, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bill No" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(200, 50, 170, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 60, 550, 300);

        jPanel3.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 830, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bill");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 0, 420, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(510, 0, 50, 40);

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("-");
        jLabel105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel105MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel105);
        jLabel105.setBounds(470, 0, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 360);

        setSize(new java.awt.Dimension(552, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void contest() {
        try {
            ct = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_management", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
        } }

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if(jComboBox1.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(rootPane, "Supplier Nameis Empty");
         jComboBox1.requestFocus();
        }else if(jTextField5.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "How Much Paid...???");
            jTextField5.requestFocus();
        }else if(jTextField6.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Deu is Empty ....\nPlease Pressed Enter..");
            jTextField5.requestFocus();
        }else{ try {
            contest();
           
                  Date dt = new Date();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
       
                String s="INSERT INTO `pharmacy_management`.`purchase_paid`(`s_name`,`number`,`paid`,`date`)VALUES (?,?,?,?)";
                ps=ct.prepareCall(s);
                     ps.setString(1,jComboBox1.getSelectedItem().toString());
                ps.setString(2,jLabel7.getText());
                ps.setString(3,jTextField5.getText());
            ps.setString(4,df.format(dt));
                int m=ps.executeUpdate();
                if(m>0){
                    JOptionPane.showMessageDialog(rootPane, "Bill Paid Success.....");
                   jTextField1.setText("0");
      jTextField2.setText("0");
      jTextField3.setText("0");
         jTextField5.setText("");
            jTextField6.setText("");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Bill Paid Failed.....");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Medicine_Info.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel105MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel105MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
          try {
              jComboBox2.removeAllItems();
              jComboBox2.addItem("Bill No");
              String s="Select `id` from `purchase_total` where `s_name`='"+jComboBox1.getSelectedItem()+"' AND `status`='main'";
              contest();
              st=ct.prepareCall(s);
              rs=st.executeQuery(s);
              while (rs.next()) {
                  jComboBox2.addItem(""+rs.getInt(1));
              }
              /* int t=0,p=0;
              try {
              
              contest();
              String mo="SELECT `mobile` FROM `pharmacy_management`.`purchase_total` WHERE `s_name`='"+jComboBox1.getSelectedItem()+"' AND `status`='main'";
              st=ct.prepareCall(mo);
              rs=st.executeQuery(mo);
              while (rs.next()) {
              jLabel7.setText(""+rs.getString(1));
              }
              
              String s="SELECT SUM(`ammount`)FROM `pharmacy_management`.`purchase_total`WHERE `status`='main' AND `s_name`='"+jComboBox1.getSelectedItem()+"'";
              st=ct.prepareCall(s);
              rs=st.executeQuery(s);
              while (rs.next()) {
              t=rs.getInt(1);
              jTextField1.setText(""+t);
              
              }
              
              
              String ss="SELECT SUM(`paid`) FROM `pharmacy_management`.`purchase_paid` WHERE `status`='main' AND `s_name`='"+jComboBox1.getSelectedItem()+"'";
              st=ct.prepareCall(ss);
              rs=st.executeQuery(ss);
              while (rs.next()) {
              p=rs.getInt(1);
              jTextField2.setText(""+p);
              
              }
              jTextField3.setText(""+(t-p));
              jTextField5.setText("");
              jTextField6.setText("");
              
              } catch (SQLException ex) {
              Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
              }
          */} catch (SQLException ex) {
              Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
 int deu=Integer.parseInt(jTextField3.getText());
  int paid=Integer.parseInt(jTextField5.getText());
 int ddeu=deu-paid;
 if(ddeu<0){
 JOptionPane.showMessageDialog(rootPane, "Sorry This is Large Ammount \n Please Cheack-it");
 }else{
 jTextField6.setText(""+ddeu);}
   
 }
        
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
void showsname(){
          try {
              jComboBox1.removeAllItems();
              jComboBox1.addItem("Supllier Name");
              
              contest();
              String s="SELECT `s_name` FROM `pharmacy_management`.`purchase_total`WHERE `status`='main' GROUP BY `s_name`";
              st=ct.prepareCall(s);
              rs=st.executeQuery(s);
              while (rs.next()) {
                 
                  jComboBox1.addItem(""+rs.getString(1));
              }
          } catch (SQLException ex) {
              Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(Level.SEVERE, null, ex);
          }
      
      


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_Bill_Paid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_Bill_Paid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
